### ISSUE TITLE
DSE Service Implementations

### ISSUE THREAD

**Issue by LukeTillman** [KillrVideo/killrvideo-nodejs#1]
Right now, we don't have a process in-place for bootstrapping DSE resources (i.e. Solr Config, Spark Jobs, etc.). Once we have a process in place for that, we'll need to fill the in the DSE implementations for services like Search and Suggested Videos.

**Comment by HadesArchitect** [comment]
@LukeTillman @SonicDMG Is it still relevant? I'd suggest to solve/close the issue.

**Comment by HadesArchitect** [comment]
Closed as inactive
