### ISSUE TITLE
Uploads Service implementation post-Azure

### ISSUE THREAD

**Issue by LukeTillman** [KillrVideo/killrvideo-nodejs#2]
The service definitions assumed we would come up with a way to implement the Uploads service that doesn't involve using Azure (like the previous C# implementation did). Now that everything is "de-Azure-fied" lets figure out what to do about the Uploads Service.

**Comment by HadesArchitect** [comment]
@LukeTillman @SonicDMG Is it still relevant? I'd suggest to solve/close the issue.

**Comment by HadesArchitect** [comment]
Closed as inactive
