### ISSUE TITLE
nodejs version?

### ISSUE THREAD

**Issue by bsmith94** [KillrVideo/killrvideo-nodejs#9]
It would be helpful to know what version of Node.js is required. v8 and v9 fail to build GRPC. It looks like 5.12.0 works, so far.

**Comment by SonicDMG** [comment]
Thanks for pointing this out.  We'll take a look and provide some more detailed info.

**Comment by SonicDMG** [comment]
v6.12.3 definitely works.  Looking at our docs here -> https://killrvideo.github.io/docs/languages/nodejs/ you are correct that we make no mention of this.  I'll be happy to add this to the documentation.

**Comment by SonicDMG** [comment]
Added a comment in the docs to reference the current working version of node.js.

**Comment by bsmith94** [comment]
Thanks for the update!
